#!/usr/bin/env node

const fs = require('fs');
const libpath = require('path');
const pixelArtMagnifier = require('./');
const { argv: [, , imagePath, sratio] } = process;
(async () => {
	const { dir, ext, name } = libpath.parse(imagePath);
	fs.writeFileSync(libpath.join(dir, `${name}x${sratio}${ext}`),await pixelArtMagnifier(imagePath, parseInt(sratio, 10)), { encoding: null });
})().catch(console.error);
